### ISSUE TITLE
Refreshing ComfyUI resets the inputs of all Loaders

### ISSUE THREAD

**Issue by Davikar** [pythongosssss/ComfyUI-Custom-Scripts#177]
Hitting the refresh button in the UI resets all the inputs of the Checkpoint and Lora loaders.
This only happens with the Pythongosss loaders, the default loaders does not reset when refreshing.

**Comment by Lawrr** [comment]
I've ran into this as well. Seems like it only happens when the first file in the loader's root folder (e.g. Lora root folder) is alphabetically before the name of the first folder.

e.g. If you have `a.safetensors` and a folder called `b`, it will happen, but if you have `b.safetensors` and a folder called `a`, it will not.

**Comment by pythongosssss** [comment]
This should now be fixed thanks to @Lawrr
