### ISSUE TITLE
Widget Defaults Properties

### ISSUE THREAD

**Issue by PrometheusDante** [pythongosssss/ComfyUI-Custom-Scripts#263]
Hello and thank you for your amazing work first of all! 
I could not find a list of all the properties you can set in the `🐍 Widget & Property Defaults:` settings. 
Could you please list them somewhere? Maybe add them to the main page, too, as that would probably help many people to get started.
A way to target all widgets in general would be appreciated as well to set global background colors or shape properties without having to do so for each individual node.

Thank you very much!

**Comment by pythongosssss** [comment]
I've added regex support on the node name to allow wildcard matches by wrapping it in `/regexhere/`

![image](https://github.com/user-attachments/assets/6ac0d328-72f5-4cd3-ad63-cbc4f8af42df)

Rule precedence is done via exact node name match, then length of the matching rule
So in the example above..:
SaveImage is blue since it is an exact match
EmptyLatentImage is green - it matches `.*` and `Image` but image is longer so it uses that
PreviewAudio is red since no other rules match

![image](https://github.com/user-attachments/assets/290abd96-4ab3-49a6-8723-74ad221f8b4a)

You can set any value that exists on the litegraph node, though I wouldn't recommend it! The most useful ones are bgcolor, color, shape
