### ISSUE TITLE
Play Sound

### ISSUE THREAD

**Issue by gobshyte** [pythongosssss/ComfyUI-Custom-Scripts#270]
I can't seem to get Play Sound to work, no matter what I connect it to, or whether I leave the sound as default or choose another file, no sound plays, and no errors occur.
What should I be connecting it to? 
What is the connection on the right hand side for? 
Please advise :)

**Comment by pythongosssss** [comment]
You should use the Play Sound generally as the last/second last node in your workflow
![image](https://github.com/user-attachments/assets/17cc4c98-eef9-46bc-96ec-f8d8de28baf8)

The input to the node is any value from any node, this controls the place in the workflow that the node is executed (e.g. if you put it after your Checkpoint Loader, it'll play the sound at the start of your workflow. If you put it next to your last Save Image node, it'll play at the end of your workflow).

The output of the node is the input, it just passes it through directly so you can use it as part of the workflow instead of having it floating (note in the screenshot above it is the same image in both preview images as that is the input)
