### ISSUE TITLE
Why is this node not installing correctly?

### ISSUE THREAD

**Issue by S0LTIS** [pythongosssss/ComfyUI-Custom-Scripts#341]
Error handling request
Traceback (most recent call last):
  File "C:\COMFYUI DIRs\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\ComfyUI\server.py", line 61, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\ComfyUI\server.py", line 73, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\model_info.py", line 65, in load_metadata
    pos = name.index("/")
          ^^^^^^^^^^^^^^^
ValueError: substring not found

![image](https://github.com/user-attachments/assets/1b495455-e79a-418f-832a-ed0fae874332)
![image](https://github.com/user-attachments/assets/50173ba1-e7c0-479e-ac5b-65fe01f4520f)
![image](https://github.com/user-attachments/assets/c10933cd-f518-4116-9a0e-c1ac979b1194)

**Comment by linksluckytime** [comment]
I also have the same problem

**Comment by S0LTIS** [comment]
> I also have the same problem

I found out that the comfyui updates have caused this node to stop working. I found a backup of an older program and replaced all directories and will never update it since it's working now. Let me know if you need this.

**Comment by S0LTIS** [comment]
However problem is not solved for latest comfyui/changes/update

**Comment by S0LTIS** [comment]
> Hi, i have the same problem, can you please drive me to the backup you found to temporarly fix the issue ? I tried update aiohttp but no success for now.
> 
> Thank you very much

https://drive.google.com/file/d/1zAkAM-a7uUPiKDv15VOw79rko_y8CJpO/view?usp=sharing

**Comment by Thecle** [comment]
Thank you so much, i will test that !

**Comment by S0LTIS** [comment]
> Thank you so much, i will test that !

you're welcome!

**Comment by Thecle** [comment]
i investigated "a bit", because i did not wanted to loose my current comfyui installation but needed to fix this problem.
i did not went to the source, but i found why does this happen : but the problem is, on windows, the string is 

`loras%2F{name of your lora}`

instead of 

`loras/{name of your lora}`

so in the file 

**ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\model_info.py**

Line 65 after : name = request.match_info["name"]
Add : name = name.replace("%2F", "/")

**ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py**

Line 57 after : name = request.match_info["name"]
Add : name = name.replace("%2F", "/")

the 2 files must looks like at those lines :

```
    name = request.match_info["name"]
    name = name.replace("%2F", "/")
    pos = name.index("/")
    type = name[0:pos]
    name = name[pos+1:]
```

My old' comfy is now fixed ;)
