### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by za-wa-n-go** [pythongosssss/ComfyUI-Custom-Scripts#68]
Is there any way to prevent the ShowText node from collapsing every time it is executed?
It is unfortunate that a large portion of the prompt is hidden each time it is executed.
Also, I would like to darken the background if possible to make the text easier to read.
<img width="682" alt="image" src="https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/118154415/7d953e31-3c10-4b0a-8974-15fb32747010">

**Comment by pythongosssss** [comment]
The node shouldnt resize to a smaller size anymore since this update https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/7c9adc1f9073d77954f84431872bfb14d4249514

To change the color you can use the `ComfyUI/web/user.css` file to define your own styles for this, 
e.g.
```css
.comfy-multiline-input:read-only {
	color: white;
	background: #111;
	opacity: 1 !important;
}
```

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/ee38c005-c505-4d9e-8185-d37120507224)
