### ISSUE TITLE
%LoraLoader|pysssss.lora_name% return value [object Object]

### ISSUE THREAD

**Issue by Davikar** [pythongosssss/ComfyUI-Custom-Scripts#83]
If I want to use the value from %LoraLoader|pysssss.lora_name% when saving an image with the file_prefix widget, I get [object Object] instead of the name of the Lora.

**Comment by pythongosssss** [comment]
This should now be fixed

**Comment by alexopus** [comment]
Thanks, can confirm the fix. Thanks!

After updating it seems that the layout of the setting dialog suffered a little:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/25933468/f8c2f53d-9243-455b-b63d-48a4e14c4d3e)
Not certain if it's because of this or something else....

Potential suspect is the default workflow selector:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/25933468/b51966e4-a656-4d64-b14c-1ed28b81058d)

**Comment by pythongosssss** [comment]
That should now be fixed!
