### ISSUE TITLE
Plz make lora and wildcard Autocomplete just like embedding

### ISSUE THREAD

**Issue by xueqing0622** [pythongosssss/ComfyUI-Custom-Scripts#86]
Plz make lora and wildcard Autocomplete just like embedding

**Comment by pythongosssss** [comment]
Loras aren't part of the prompt, so how would you want that to work?
For wildcards you can just add your files to the list via the setting

**Comment by xueqing0622** [comment]
Here are lora working in text encoder and translate to condition
https://github.com/skfoo/ComfyUI-Coziness

**Comment by NeedsMoar** [comment]
There are conditioning nodes that parse this out too, although I have no idea how they're supposed to work with no model output unless that's implicit which is kinda worse since it's hiding information about the underlying flow of things.  They really aren't part of the prompt (their keywords are, but the Coziness node doesn't seem to look those up and insert them nor does that work for everything) and wouldn't be in-place there.

**Comment by AsuraAce** [comment]
> For wildcards you can just add your files to the list via the setting

could you explain how exactly? i would like to have similar functionality as the a1111 extension in order to navigate the wildcard folder structure. 

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

**Comment by pythongosssss** [comment]
This has been done

**Comment by xueqing0622** [comment]
thx, it works!
